[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [
    { access = "read", path = "./lib/dss-test/script/input/"},
    { access = "read", path = "./out/ArbitrumDomain.sol/ArbSysOverride.json"},
    { access = "read-write", path = "./spellblock.txt"}
]

[rpc_endpoints]
goerli = "${ETH_RPC_URL}"

# See more config options https://github.com/gakonst/foundry/tree/master/config
