name: Tests

on: [push, pull_request]

env:
  FOUNDRY_PROFILE: ci
  ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}

jobs:
  tests:
    strategy:
      fail-fast: true

    name: Spell Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: make test
